# Generated by Django 4.2.23 on 2025-09-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
