# Generated by Django 4.2.23 on 2025-09-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/default_avatar.png', null=True, upload_to='images/'),
        ),
    ]
