# Generated by Django 4.2.23 on 2025-09-05 08:58

from django.db import migrations

def set_default_avatar(apps, schema_editor):
    User = apps.get_model('users', 'User')  # replace with your app name
    default_avatar = 'defaults/default_avatar.png'
    for user in User.objects.all():
        if not user.profile_image:  # If no profile image
            user.profile_image = default_avatar
            user.save(update_fields=['profile_image'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.RunPython(set_default_avatar),
    ]
