# Generated by Django 4.2.23 on 2025-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shelf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
