# Generated by Django 4.2.23 on 2025-09-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_alter_shelf_options_shelf_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shelf_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shelves.shelf')),
            ],
        ),
    ]
