# Generated by Django 4.2.23 on 2025-09-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_shelfimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='currently_available',
            field=models.BooleanField(default=True),
        ),
    ]
