# Generated by Django 4.2.23 on 2025-09-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_shelf_currently_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='event_type',
            field=models.CharField(choices=[('Retail / Pop-up store', 'Retail / Pop-up store'), ('Art Exhibit / Gallery', 'Art Exhibit / Gallery'), ('Corporate Event', 'Corporate Event')], default='Retail / Pop-up store', max_length=50),
        ),
    ]
