# Generated by Django 4.2.23 on 2025-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_shelf_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='event_type',
            field=models.CharField(choices=[('Retail / Pop-up store', 'Retail / Pop-up store'), ('Art Exhibit / Gallery', 'Art Exhibit / Gallery'), ('Corporate Event', 'Corporate Event'), ('Workshop / Seminar', 'Workshop / Seminar'), ('Food / Beverage Tasting', 'Food / Beverage Tasting'), ('Book / Art Launch', 'Book / Art Launch'), ('Other', 'Other')], default='Retail / Pop-up store', max_length=50),
        ),
    ]
