# Generated by Django 4.2.23 on 2025-09-08 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('shelves', '0006_alter_shelf_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_inventory', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shelves.shelf')),
            ],
            options={
                'unique_together': {('shelf', 'product', 'brand')},
            },
        ),
    ]
